Mod a little

diff --git a/dotzshrc b/dotzshrc
--- a/dotzshrc
+++ b/dotzshrc
@@ -158,6 +158,9 @@ function serve(){
     elif [[ -f "$1" ]]; then
         dir="$(dirname "$1")"
         file="$(basename "$1")"
+    else
+        echo "Not Found $1" >&2
+        return 1
     fi
 
     if [[ -n "$dir" ]]
